va_out_dir:
  path:
  - ''
  - Rambow_dataset
  - filtered_var
  root: ..
va_depth_minimum: 3
va_missing_values_max: 0.4
va_minumum_median_total: 12
va_minumum_median_mutation: 4
va_verified_genes:
- ARPC2
- CCT8
- PRAME
- COL1A2
- HNRNPC
- RPL5
va_list_genes:
- A2M
- AAMP
- ABCA5
- ABCA8
- ABCF1
- ABLIM1
- ACAP2
- ACOX3
- ACTR3
- AFF4
- AK2
- AKAP12
- ALDH9A1
- ALKBH2
- AMOTL1
- ANGPTL4
- ANKRD17
- ANKRD44
- ANP32E
- AP3B1
- APEX1
- ARCN1
- ARF1
- ARHGAP5
- ARHGEF26
- ARID5B
- ARL8B
- ARPC2
- ARPC5L
- ARV1
- ASL
- ASMTL
- ATAD3B
- ATG5
- ATP1B3
- ATP5MD
- ATP5MG
- ATRAID
- ATXN10
- AZIN1
- B3GNT2
- B4GALT3
- BABAM2
- BACH1
- BCAS2
- BCAS3
- BCLAF1
- BEX3
- BNIP2
- BRAF
- BRD2
- BZW1
- C1orf21
- C1R
- C20orf194
- C5orf22
- C5orf58
- C6orf47
- C7orf50
- C8orf33
- CALCOCO2
- CALHM2
- CAMSAP2
- CANX
- CAPZA2
- CBLL1
- CCDC28A
- CCDC66
- CCDC80
- CCNG1
- CCNI
- CCSER2
- CCT3
- CCT5
- CCT6A
- CCT8
- CDK16
- CDK20
- CDKN2AIP
- CERS2
- CFAP97
- CHD1
- CHD1L
- CHD9
- CHMP2A
- CHPF
- CHPT1
- CKLF
- CLIC1
- CLIP1
- CMPK1
- CNN3
- COG3
- COL1A2
- COL9A3
- COPA
- COPG2
- COPS9
- COQ8B
- COX7A2
- CRB1
- CREB3L4
- CSAG1
- CTNNA1
- CTSA
- CTSD
- CTSK
- CUTA
- CYCS
- CYTL1
- DAG1
- DDX42
- DENND5A
- DGUOK
- DHRSX
- DIMT1
- DOHH
- DPAGT1
- DRG2
- DTX2
- DUS3L
- DUSP11
- ECHDC1
- EEF1AKMT2
- EFTUD2
- EGFR
- EGR1
- EID1
- EIF3H
- EIF3I
- EIF3M
- ELMOD2
- ELOVL5
- ELP6
- ENOX2
- ERCC2
- ESD
- EXOC4
- F2R
- F2RL2
- FAAP20
- FAM184B
- FAM185A
- FAM217B
- FARSB
- FCGR2A
- FCMR
- FDFT1
- FLRT3
- FMOD
- FNDC3A
- FTH1
- FTSJ3
- FUBP1
- FUCA2
- GFM1
- GFM2
- GHITM
- GLRX3
- GNAI1
- GNAI2
- GNB2
- GOLGA8A
- GPATCH4
- GPCPD1
- GPD2
- GPR37
- GPSM2
- GPX1
- GRB2
- GRIPAP1
- H1F0
- HACD1
- HACD3
- HADHB
- HDAC2
- HDLBP
- HEXIM2
- HLA-A
- HLA-B
- HLA-C
- HLA-E
- HMCN1
- HNRNPC
- HOXB7
- HSF1
- HSP90B1
- IFI44
- IFIT5
- IGFBP7
- ILF3
- IP6K2
- IPO4
- ITGA4
- ITGB1BP1
- ITPRID2
- IVNS1ABP
- KARS
- KLC4
- KNOP1
- LAMTOR5
- LBR
- LGALS3
- LIN9
- LONP1
- LRPPRC
- LRRC28
- LRRC41
- LRRFIP1
- LSM10
- LSR
- LTA4H
- LUC7L
- LYAR
- LYST
- MAD1L1
- MAGEF1
- MAPKAPK5
- MAPRE2
- MARCHF7
- MAVS
- MDM4
- MEIS1
- MESD
- MIA3
- MIS12
- MKI67
- MOAP1
- MPLKIP
- MRPL13
- MRPL15
- MRPL18
- MRPL20
- MRPL33
- MRPL39
- MRPS17
- MRPS28
- MRPS5
- MTDH
- MTLN
- MTR
- MTUS1
- MX2
- NAA20
- NAA25
- NACAD
- NAP1L1
- NAT10
- NAV1
- NAXE
- NBDY
- NBEAL1
- NCOR1
- NDUFA12
- NDUFC2-KCTD14
- NDUFS2
- NEDD1
- NEU1
- NFE2L2
- NFIA
- NIPA2
- NOB1
- NOL7
- NOLC1
- NONO
- NOP53
- NOTCH2
- NPM1
- NR1H2
- NR4A1
- NRDC
- NUMA1
- NUP205
- NUP35
- NUPR2
- OAS1
- OCIAD1
- OGDH
- OGFOD2
- OSTC
- OSTM1
- P4HB
- PAPSS1
- PARL
- PARP1
- PARP10
- PARP4
- PCBP1
- PCBP2
- PCDH1
- PCDHB3
- PCNX3
- PCNX4
- PDCD5
- PDE7B
- PDXDC1
- PECR
- PGK1
- PHAX
- PHLDA1
- PI4KA
- PIGK
- PILRB
- PIMREG
- PLA2G4C
- PLEKHG3
- PLEKHO1
- PLRG1
- PLS3
- PLXNB2
- PNPLA6
- PNRC1
- POGLUT2
- POLD2
- POMC
- POMP
- PON2
- POP7
- POPDC3
- POSTN
- PPM1M
- PPP1R15B
- PPP1R7
- PPP2R1A
- PPP4R1
- PRAME
- PRDX1
- PRDX6
- PRELP
- PRKD1
- PRKDC
- PRPF40A
- PRRC2C
- PSMA1
- PSMA6
- PSMC4
- PSMD1
- PSPH
- PTGES3
- PTPRJ
- PTPRZ1
- PTTG1IP
- PUM1
- PYGL
- RACK1
- RAE1
- RALY
- RANBP1
- RASA2
- RBFOX2
- RBM23
- RBM48
- RBM4B
- RBM6
- RBSN
- RCN2
- RCN3
- REX1BD
- RFTN2
- RGS2
- RIC8A
- RIOK3
- RIOX2
- RNASEK
- ROR1
- RPL10A
- RPL11
- RPL12
- RPL14
- RPL22
- RPL32
- RPL4
- RPL5
- RPL9
- RPLP2
- RPN2
- RPUSD3
- RTL8A
- RTN3
- RTN4IP1
- RWDD1
- SAMHD1
- SARS
- SASH1
- SCAND1
- SCARB1
- SEC31A
- SEMA3C
- SENP5
- SF3B1
- SFRP1
- SFSWAP
- SGO1
- SIGIRR
- SLC25A24
- SLC26A2
- SLC33A1
- SLC35F1
- SLC38A2
- SLC3A2
- SLC41A3
- SLC44A2
- SLC6A15
- SLITRK6
- SMARCA1
- SMARCA5
- SMG7
- SMG9
- SMIM8
- SNX1
- SNX19
- SNX2
- SOX6
- SPOUT1
- SPPL2B
- SRP14
- SRP9
- SRSF9
- SSBP1
- STARD13
- STEAP1B
- STK10
- STK24
- STX10
- SUCLG1
- SULT1A1
- SUOX
- SYNGR2
- SYPL1
- TAF11
- TAF8
- TALDO1
- TANC1
- TARS2
- TBCE
- TBX2
- TDRKH
- TEAD4
- TEFM
- TIPRL
- TMCO3
- TMEM131L
- TMEM242
- TMEM53
- TNFRSF1A
- TNS3
- TP53RK
- TRABD
- TRAPPC11
- TRPT1
- TSPYL1
- TTC4
- TTI1
- TTLL4
- TUBB4A
- TXNDC17
- TYMS
- UBD
- UBR7
- UFSP2
- UPK3BL1
- UQCC3
- URGCP
- URI1
- USP53
- VAPB
- VMP1
- VPS35L
- VPS41
- VPS72
- WDR34
- WWTR1
- XRCC5
- YLPM1
- YY1AP1
- ZBTB38
- ZBTB41
- ZC3H13
- ZC3H15
- ZC3HC1
- ZFP36L1
- ZKSCAN8
- ZMYM4
- ZNF106
- ZNF136
- ZNF146
- ZNF239
- ZNF480
- ZNF512
- ZNF518B
- ZNF618
- ZNF76
- ZNF776
- ZNF786
- ZNHIT1
- ZPR1
